name: Data Preprocessing Pipeline

on:
  # Trigger otomatis saat push ke branch main/master
  push:
    branches:
      - main
      - master
    paths:
      - 'dataset_raw/**'
      - 'preprocessing/automate_Rehandra.py'
  
  # Trigger manual via GitHub UI
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn
      
      # 4. Run preprocessing script
      - name: Run Preprocessing
        run: |
          cd preprocessing
          python automate_Rehandra.py
      
      # 5. Commit dan push hasil preprocessing
      - name: Commit Preprocessed Data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add preprocessing/dataset_preprocessing/
          git diff --staged --quiet || git commit -m "Auto-update: Preprocessed data generated [skip ci]"
          git push
